/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/ferrari_f50_dark_matte.gltf -t
*/

import * as THREE from 'three';
import React from 'react';
import {useGLTF} from '@react-three/drei';
import {GLTF} from 'three-stdlib';
import {useCustomization} from '../../contexts';

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_57: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_60: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshPhysicalMaterial;
    FERRARI_F50: THREE.MeshPhysicalMaterial;
    Ferrari_F50_1995_by_Alex_Ka: THREE.MeshStandardMaterial;
    material_3: THREE.MeshStandardMaterial;
    blackaluminium: THREE.MeshPhysicalMaterial;
    blackchrome: THREE.MeshStandardMaterial;
    blackmatte: THREE.MeshStandardMaterial;
    blackplastic: THREE.MeshPhysicalMaterial;
    bottom: THREE.MeshStandardMaterial;
    brakedisc: THREE.MeshStandardMaterial;
    brakelight: THREE.MeshPhysicalMaterial;
    chrome: THREE.MeshStandardMaterial;
    chrome_details: THREE.MeshStandardMaterial;
    designo_plastic: THREE.MeshStandardMaterial;
    door_lock: THREE.MeshStandardMaterial;
    engine_glass: THREE.MeshPhysicalMaterial;
    engine_rear: THREE.MeshStandardMaterial;
    engine_up: THREE.MeshStandardMaterial;
    exhaust_black_chrome: THREE.MeshStandardMaterial;
    exhaust_bronze: THREE.MeshStandardMaterial;
    exhaust_chrome: THREE.MeshStandardMaterial;
    exhaust_hole: THREE.MeshStandardMaterial;
    ferrari_support_logo: THREE.MeshStandardMaterial;
    floor: THREE.MeshStandardMaterial;
    gril_front: THREE.MeshStandardMaterial;
    grill_front_side: THREE.MeshStandardMaterial;
    grill_rear: THREE.MeshPhysicalMaterial;
    headlight1: THREE.MeshPhysicalMaterial;
    headlight2: THREE.MeshStandardMaterial;
    headlightglass: THREE.MeshPhysicalMaterial;
    hood_emblem: THREE.MeshStandardMaterial;
    horse: THREE.MeshStandardMaterial;
    interior: THREE.MeshStandardMaterial;
    italy_logo: THREE.MeshStandardMaterial;
    mid_brakelight: THREE.MeshPhysicalMaterial;
    mirror_interior: THREE.MeshStandardMaterial;
    mirrors: THREE.MeshStandardMaterial;
    pininfarina_chrome: THREE.MeshStandardMaterial;
    plastic_front: THREE.MeshPhysicalMaterial;
    plastic_front_side: THREE.MeshPhysicalMaterial;
    plate_F: THREE.MeshStandardMaterial;
    plate_R: THREE.MeshStandardMaterial;
    plate_ferrari_logo: THREE.MeshPhysicalMaterial;
    radiator: THREE.MeshStandardMaterial;
    radiator_side: THREE.MeshStandardMaterial;
    rim1: THREE.MeshStandardMaterial;
    rim2: THREE.MeshStandardMaterial;
    rim_emblem: THREE.MeshPhysicalMaterial;
    side_horse_black: THREE.MeshPhysicalMaterial;
    side_windo_horse_logo: THREE.MeshStandardMaterial;
    sideline_black_plastic: THREE.MeshStandardMaterial;
    suport1: THREE.MeshPhysicalMaterial;
    suport2: THREE.MeshStandardMaterial;
    suspension: THREE.MeshStandardMaterial;
    tire: THREE.MeshStandardMaterial;
    tire_side: THREE.MeshStandardMaterial;
    turnlight_front: THREE.MeshPhysicalMaterial;
    turnlight_side: THREE.MeshPhysicalMaterial;
    windo: THREE.MeshPhysicalMaterial;
  };
};

export function Ferrari2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/ferrari_f50_dark_matte.gltf') as GLTFResult;

  const { carColor, carTexture, isWheelsRotation } = useCustomization();

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.FERRARI_F50} />
        <mesh geometry={nodes.Object_4.geometry}>
          <meshStandardMaterial
            color={carColor.color}
            roughness={carTexture.roughness}
            metalness={carTexture.metalness}
          />
        </mesh>
        {/*<mesh geometry={nodes.Object_5.geometry} material={materials.material_3} />*/}
        <mesh geometry={nodes.Object_6.geometry} material={materials.blackaluminium} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.blackchrome} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.blackmatte} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.blackplastic} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.bottom} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.brakedisc} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.brakelight} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.chrome_details} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.designo_plastic} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.door_lock} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.engine_glass} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.engine_rear} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.engine_up} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.exhaust_black_chrome} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.exhaust_bronze} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.exhaust_chrome} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.exhaust_hole} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.ferrari_support_logo} />
        {/*<mesh geometry={nodes.Object_25.geometry} material={materials.floor} />*/}
        <mesh geometry={nodes.Object_26.geometry} material={materials.gril_front} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.grill_front_side} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.grill_rear} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.headlight1} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.headlight2} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.headlightglass} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.hood_emblem} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.horse} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.interior} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.italy_logo} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.mid_brakelight} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.mirror_interior} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.mirrors} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.pininfarina_chrome} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.plastic_front} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.plastic_front_side} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.plate_F} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.plate_R} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.plate_ferrari_logo} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.radiator} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.radiator_side} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.rim1} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.rim2} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.rim_emblem} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.side_horse_black} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.side_windo_horse_logo} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.sideline_black_plastic} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.suport1} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.suport2} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.suspension} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.tire_side} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.turnlight_front} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.turnlight_side} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.windo} />
      </group>
    </group>
  );
}

useGLTF.preload('./models/ferrari_f50_dark_matte.gltf');
